### ISSUE TITLE
1st Week

### ISSUE THREAD

**Issue by z1ggy-o** [JsoupMaster/jsoup#3]
`jsoup` parser related part analysis.

- [x] UML
- [x] Corresponding code
- [x] Existing design pattern analysis
- [x] Update wiki

**Comment by hsebs** [comment]
## UML of parser
![UML](https://user-images.githubusercontent.com/19328795/69492151-e1fb6180-0ee1-11ea-87c2-293be48bd955.jpg)

## Existing Patterns
### State Pattern
![UML](https://user-images.githubusercontent.com/19328795/69900551-255d4080-13b8-11ea-8da4-05aef309f4d2.jpg)
#### TokeniserState
* State Interface
  * Reason : enumeration which has abstract method

![UML](https://user-images.githubusercontent.com/19328795/69900537-f0e98480-13b7-11ea-89cb-aa628c4f6939.jpg)
#### HtmlTreeBuilderState
* State Interface
  * Reason : enumeration which has abstract method
### Strategy pattern
![UML](https://user-images.githubusercontent.com/19328795/69900756-b7664880-13ba-11ea-928d-64ce33157529.jpg)
#### Parser
* Context
  * Reason : Receive an object that inherits an abstract class and use methods of the object as subroutine.
#### TreeBuilder
* Strategy
  * Reason : Interface for object which stored in Parser.
### Facade pattern
![UML](https://user-images.githubusercontent.com/19328795/69900605-ec719b80-13b8-11ea-88dd-f5a35d21ddbd.jpg)

#### Paser
* Facade
  * Reason : Simplify interface by merging tightly coupled methods.
### Singleton pattern
#### Tag
* All objects are created statically.
## Problem
* TokenQueue is independent with the others in Parser package
* Parser has two design pattern which conflict with each other. Strategy pattern is DIP, but Facade Pattern violates DIP.

**Comment by z1ggy-o** [comment]
## How it works

1. `Jsoup` is the entry point of the whole program.
2. `Jsoup` will call `Parser`'s method to parse a given string or URI.
3. `Parser` does not do the real parsing works. It just passes the request to `TreeBuilder`.
4. In `TreeBuilder`, there is a `parse()` method, it will:
   1. Do initialization by `initialiseParse()` method.
   2. call `runParse()` to start parsing.
      1. `runParse()` get token from `Tokeniser`
      2. then depend on the type of `Token`, call corresponding `process()` method to build DOM tree
5. `TreeBuilder` is an abstract class, there are two children concrete class of it:
   1. `HtmlTreeBuilder` for HTML targets.
   2. `XmlTreeBuilder` for XML targets.
6. `HtmlTreeBuilderState` and `TokeniserState` have similar working flow:
   1. Depends on the state, use different `process()` to parsing tokens.
   2. Depends on the state, use different `read()` method to read tokens.
   3. They are both `enum` class, each state of them contains an overloading method.

## Existing Patterns

### Template Method Pattern

#### Class Diagram

![image](https://user-images.githubusercontent.com/19348185/68832840-53bef880-06f5-11ea-9895-e37ebd6645dd.png)

#### Corresponding Codes

`TreeBuilder`'s `runParser()` start parsing.

```java
abstract class TreeBuilder {
// other codes
    Document parse(Reader input, String baseUri, Parser parser) {
        initialiseParse(input, baseUri, parser);
        runParser();
        return doc;
    }
}

protected void runParser() {
    while (true) {
      Token token = tokeniser.read();
      process(token);
      token.reset();

      if (token.type == Token.TokenType.EOF)
          break;
    }
}

protected abstract boolean process(Token token);
```

`HtmlTreeBuilder` inherit `TreeBuilder`, implements `process()`.
```java
public class HtmlTreeBuilder extends TreeBuilder {
  // other codes

  @Override
  protected boolean process(Token token) {
    currentToken = token;
    return this.state.process(token, this);
  }
}
```

`XmlTreeBuilder` also implements its `process()` and override `initialiseParse()`
```java
public class XmlTreeBuilder extends TreeBuilder {

    @Override
    protected boolean process(Token token) {
        ...
    }
}
```

#### Reasons

**Template method pattern** defines the skeleton of an algorithm as a set of steps. Some methods of the algorithm have to be implemented by the subclasses, and these methods are abstract methods in the superclass.

Here, `TreeBuilder` defines an algorithm `runParse()`, it call `initializeParse()` and `process()` to parsing the given contents. `process()` is an abstract method. `HtmlTreeBuilder` and `XmlTreeBuilder` are subclasses of `TreeBuilder` and implement their own `process()` methods.

## Problems

1. `Parser` constructor needs a `TreeBuilder`, `TreeBuilder` also contains `Parser` object. Is this a good design?
2. `TokeniserState` and `HtmlTreeBuilderState` depends on the **states** to call different `read()` and `process()`methods, is this a pattern?

**Comment by compass0** [comment]
2019.11.17
Tag class -> Singleton
