### ISSUE TITLE
3rd Week

### ISSUE THREAD

**Issue by hsebs** [JsoupMaster/jsoup#4]
`jsoup` nodes, helper and select related part analysis.

- [x] UML
- [x] Corresponding code
- [x] Existing design pattern analysis
- [x] Update wiki

**Comment by hsebs** [comment]
## UML of nodes
![UML](https://user-images.githubusercontent.com/19328795/69492169-fe979980-0ee1-11ea-8486-0eae189c74ae.jpg)
## Existing Patterns
### Composite pattern
#### Node
* Component Interface
  * Reason : A common interface of the composite class and leaf classes.
#### Element
* Composite Interface
  * Reason : Contains multiple component objects.
#### LeafNode
* Leaf Interface
  * Reason : Does not contains a leafnode object.
## UML of select
![UML](https://user-images.githubusercontent.com/19328795/69493050-4a9c0b80-0eed-11ea-819a-7807c2ef61e5.jpg)

## Existing Pattern
### Strategy pattern
#### NodeTraversor
* Context 
  * Reason : Store object that inherits an abstract class and use abstract method of it as subroutine of method.
#### NodeVisitor
* Strategy Interface
  * Reason : Interface for object which stored in NodeTraversor.

## UML of helper
![UML](https://user-images.githubusercontent.com/19328795/69710725-3fdab400-1143-11ea-8360-8157048128a3.jpg)
## Problems
* ChangeNotifyingArrayList does not have a relation with the other in the package.

## UML of internal
![UML](https://user-images.githubusercontent.com/19328795/69709742-57b13880-1141-11ea-9418-a8b27a9f8918.jpg)
## Problems
* Classes does not have a relation with each other in the package.

**Comment by z1ggy-o** [comment]
## `nodes` Package

![image](https://user-images.githubusercontent.com/19348185/69898554-5c265d00-139e-11ea-857c-ebbfc1ce94f4.png)

`Node` is the base `abstract` class. It provides a base framework and some methods like insert, remove.

`Element` is a class for HTML elements. It has three components: tag name, attributes, and child nodes.
Child notes can be text nodes and other elements.  
`Element` use lots of methods of `Selecter` to handle CSS query.  
`Element` has three children class: `FormElement`, `Document` and `PseudoTextElement`. `FormElement` has some methods for HTML from, like `submit()`.  `PseudoTextElement` let `TextNode` can be selected with `Selector` sytax.

`LeafNode` is the base node for some specific HTML contents, like text, comment, data...

### Existing Patterns

#### Composite Pattern

```java
public class Element extends Node {
    private static final List<Node> EMPTY_NODES = Collections.emptyList();
}

abstract class LeafNode extends Node {
    private static final List<Node> EmptyNodes = Collections.emptyList();
}
```

`Element` and `LeafNode` are children classes of `Node` Class.  Both `Element` and `LeafNode` have a list that contains `Node`. And there are some other classes inherit from `Element` and `LeafNode`.

`Node` is the `component`, `Element` and `LeafNode` are the `composite` class. 

## `select` Package

![image](https://user-images.githubusercontent.com/19348185/69898852-d3112500-13a1-11ea-8818-b54ebf1c1a9a.png)

`Selector` and `QueryParser` handle the CSS-like query.

### Existing Patterns

#### Strategy Pattern

```java
public class NodeTraversor {
    private NodeVisitor visitor;

    public static void traverse(NodeVisitor visitor, Node root) {
        Node node = root;
        int depth = 0;
        
        while (node != null) {
            visitor.head(node, depth);
            if (node.childNodeSize() > 0) {
                node = node.childNode(0);
                depth++;
            } else {
                while (node.nextSibling() == null && depth > 0) {
                    visitor.tail(node, depth);
                    node = node.parentNode();
                    depth--;
                }
                visitor.tail(node, depth);
                if (node == root)
                    break;
                node = node.nextSibling();
            }
        }
    }

    public static void filter(NodeFilter filter, Elements elements) {
        Validate.notNull(filter);
        Validate.notNull(elements);
        for (Element el : elements)
            if (filter(filter, el) == FilterResult.STOP)
                break;
    }
```

`NodeTraversor` let `NodeVisitor` and `NodeFilter` to choose how to implement the `head()` and `tail()` method. And `NodeTraversor` can change visitor and filter at runtime.

**Comment by z1ggy-o** [comment]
## Package Dependency

![image](https://user-images.githubusercontent.com/19348185/69898967-7dd61300-13a3-11ea-898f-1266fc608bca.png)

### Circle Dependent

- jsoup, helper
- internal, helper
- jsoup, nodes
- helper, nodes
- jsoup, parser
- parser, helper
- parser, node
- select, internal
- node, select
- select, parser

**Comment by z1ggy-o** [comment]
Also many Iterator Pattern. Like in `Attributes` Class :

```java
private class DatasetIterator implements Iterator<Map.Entry<String, String>> {
            private Iterator<Attribute> attrIter = attributes.iterator();
            private Attribute attr;
            public boolean hasNext() {
                while (attrIter.hasNext()) {
                    attr = attrIter.next();
                    if (attr.isDataAttribute()) return true;
                }
                return false;
            }

            public Entry<String, String> next() {
                return new Attribute(attr.getKey().substring(dataPrefix.length()), attr.getValue());
            }

            public void remove() {
                attributes.remove(attr.getKey());
            }
        }
```
