### ISSUE TITLE
4th Week

### ISSUE THREAD

**Issue by hsebs** [JsoupMaster/jsoup#5]
- [x] Add Functions
- [x] Reduce dependence

**Comment by z1ggy-o** [comment]
## `Tag` Class Problem

In `org.jsoup.parser`'s `Tag` Class.

There is a `HashMap` in `Tag` that contains all the pre-defined tags. Each tag is stored into the `Map` as a `<String, Tag>` pair. Clients get `Tag` instance by passing tag names `valueOf`.

```java
public static Tag valueOf(String tagName, ParseSettings settings) {
        Validate.notNull(tagName);
        Tag tag = tags.get(tagName);

        if (tag == null) {
            tagName = settings.normalizeTag(tagName);
            Validate.notEmpty(tagName);
            tag = tags.get(tagName);

            if (tag == null) {
                // not defined: create default; go anywhere, do anything! (incl be inside a <p>)
                tag = new Tag(tagName);
                tag.isBlock = false;
            }
        }
        return tag;
    }
```

`Tag` constructor is `private` and all the pre-defined tags are inserted into the `HashMap` at `static` initialization part. When unknow tag names are passed to `valueOf` method, it will create a `Tag` instance and return it. This may create a lot of instances of the same unknown `Tag`.

**Comment by z1ggy-o** [comment]
## `Tag` Class Improvement

To avoid wasting memory, here we change the unknown `Tag` generation part by `Singleton` pattern.

```java
public static Tag valueOf(String tagName, ParseSettings settings) {
        Validate.notNull(tagName);
        // zgy: Start
        Tag tag = tags.get(tagName);

        if (tag == null) {
            tagName = settings.normalizeTag(tagName);
            Validate.notEmpty(tagName);
            // zgy: Second 
            tag = tags.get(tagName);

            if (tag == null) {
            // zgy: Handle multithreading
                synchronized(Tag.class) {
                    tag = tags.get(tagName);
                    if (tag == null) {
                        // not defined: create default; go anywhere, do anything! (incl be inside a <p>)
                        tag = new Tag(tagName);
                        tag.isBlock = false;
                        register(tag);
                    }
                }
            }
        }
        return tag;
    }
```

Use double-check to avoid unnecessary locking. Only serialize the access when we need to add new `Tag` into the HashMap.

Check unit test code in `TagTest.java` and `TagTestMultithreading.java`.

**Comment by hsebs** [comment]
## `TokenQueue` Class Problem
`TokenQueue` class In `org.jsoup.nodes` package does not have relation with the others.

`TokenQueue` class only works with the` QueryParser` class in the `org.jsoup.select` package.
https://github.com/JsoupMaster/jsoup/blob/8d1d503913a68e549b5c4a94717c62cf3f64507a/src/main/java/org/jsoup/select/QueryParser.java#L17-L21

**Comment by hsebs** [comment]
## `TokenQueue` Class Improvement
Move `TokenQueue` class from `org.jsoup.nodes` to `org.jsoup.select` to reduce package dependency.

**Comment by z1ggy-o** [comment]
> ## `Tag` Class Improvement
> To avoid wasting memory, here we change the unknown `Tag` generation part by `Singleton` pattern.
>
> Check unit test code in `TagTest.java` and `TagTestMultithreading.java`.

Cannot pass all the unit test. Need modification.

**Comment by z1ggy-o** [comment]
Make `Tag` Singleton for unknown tags needs to modify all the parsing parts related to unknown tags. Chose not to do the `Tag` modification.

**Comment by z1ggy-o** [comment]
Add three file download functionality.

Three related patterns:

- Facade Pattern: `Downloader` class provides a simple API to let users download files they want.
- Template Pattern: `ImageDownloader`, `UrlsDownloader` and `HtmlDownloader` implement their own `downloadTarget()`, other methods are same.
- Simple Factory: Add abstraction between users and concrete `Downloader` classes.

![image](https://user-images.githubusercontent.com/19348185/70141239-f574ac80-16d9-11ea-83b1-a0651e310132.png)

**Comment by hsebs** [comment]
## `Selector` Class Improvement
### Function Improvement
`selectLast` method is added. 

## `Collector` Class Improvement
### Function Improvement
`findLast` method is added.

## `NodeTraversor` Class Improvement
### Function Improvement
`HeadToTailTraversor` Class is added that replaces the old `NodeTraversor` Class. 
`TailToHeadTraversor` Class is added that is used in `findLast` method of `Collector` Class.
### Design Pattern Improvement
#### Old
![UML](https://user-images.githubusercontent.com/19328795/70142731-433ee400-16dd-11ea-9678-f9b422acd86e.jpg)
* Strategy Pattern
  * It is not used.
#### New
![UML](https://user-images.githubusercontent.com/19328795/70142574-e5120100-16dc-11ea-87dd-013531f5d5c0.jpg)

* Template Method Pattern
  * `NodeTraversor` Class is changed into Interface. 
  * `HeadToTailTraversor` Class and `TailToHeadTraversor` Class inherts `NodeTraversor` Interface.

## `Node` Class Improvement
### Function Improvement
User can select traverse algorithm(`NodeTraversor`).
### Design Pattern Improvement
#### Old
![UML](https://user-images.githubusercontent.com/19328795/70141605-c90d6000-16da-11ea-9cf7-2c3f1023d6f9.jpg)
* Visitor Pattern
  * `NodeVisitor` follows Visitor Pattern. But `NodeTraversor` isn't.
#### New
![UML](https://user-images.githubusercontent.com/19328795/70141830-33be9b80-16db-11ea-9c57-ec74948b6270.jpg)
* Visitor Pattern
  * `traverse` method takes `NodeTraversor` object.
